import type { Metadata } from "next";
import { Merriweather, Lora } from "next/font/google";
import "./globals.css";
import { cn } from '@/lib/utils'
import { ThemeProvider } from "@/components/theme-provider"

const fontMerriweather = Merriweather({
    variable: "--font-merriweather",
    subsets: ["latin"],
    weight: ['300', '400', '500', '600', '700']
});

const fontLora = Lora({
    variable: "--font-lora",
    subsets: ["latin"],
    weight: ['400', '500', '600', '700']
});

export const metadata: Metadata = {
    title: "Care Plus",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={cn("h-full", "antialiased", fontMerriweather.variable, fontLora.variable, )}
            suppressHydrationWarning
        >
            <body className={cn('min-h-screen dark:bg-dark-300 font-merriweather antialiased', fontMerriweather.variable)}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
