import type { Metadata } from "next";
import { Merriweather, Lora, Geist } from "next/font/google";
import "./globals.css";
import {cn} from '@/lib/utils'

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const fontMerriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
  weight: ['300', '400', '500', '600', '700']
});

const fontLora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ['400', '500', '600', '700']
});

export const metadata: Metadata = {
  title: "Care Plus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", fontMerriweather.variable, fontLora.variable, "font-sans", geist.variable)}
    >
      <body className={cn('min-h-screen bg-dark-300 font-merriweather antialiased', fontMerriweather.variable)}>{children}</body>
    </html>
  );
}
